// convex/seedData.ts
export const SEED_PROPERTIES = [
  {
    id: "prop_001",
    address: "123 Collins Street, Melbourne VIC 3000",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    carSpaces: 1,
    price: 850000,
    landSize: undefined,
    buildingSize: 95,
    yearBuilt: 2018,
    features: ["City views", "Gym", "Concierge", "Rooftop terrace"],
    description:
      "Modern 2-bedroom apartment in the heart of Melbourne CBD with stunning city views.",
    images: ["https://via.placeholder.com/400x300?text=Melbourne+Apartment"],
    listingAgent: "Sarah Chen - Ray White Melbourne",
    inspectionTimes: ["Sat 2:00-2:30 PM", "Wed 6:00-6:30 PM"],
    auctionDate: "2025-02-15",
    priceGuide: "$800,000 - $880,000",
  },
  {
    id: "prop_002",
    address: "45 Ocean Drive, Bondi Beach NSW 2026",
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    price: 2100000,
    landSize: 350,
    buildingSize: 180,
    yearBuilt: 1995,
    features: ["Ocean views", "Renovated kitchen", "Private garden", "Walk to beach"],
    description:
      "Charming 3-bedroom house just 200m from Bondi Beach with ocean glimpses.",
    images: ["https://via.placeholder.com/400x300?text=Bondi+Beach+House"],
    listingAgent: "Michael Torres - LJ Hooker Bondi",
    inspectionTimes: ["Sat 11:00-11:45 AM", "Thu 5:30-6:00 PM"],
    auctionDate: "2025-02-22",
    priceGuide: "$2.0M - $2.2M",
  },
  {
    id: "prop_003",
    address: "78 Chapel Street, South Yarra VIC 3141",
    type: "townhouse",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    price: 1350000,
    landSize: 120,
    buildingSize: 165,
    yearBuilt: 2020,
    features: ["New build", "Private courtyard", "Designer finishes", "Walk to trams"],
    description: "Contemporary 3-bedroom townhouse in prestigious South Yarra location.",
    images: ["https://via.placeholder.com/400x300?text=South+Yarra+Townhouse"],
    listingAgent: "Emma Wilson - Marshall White",
    inspectionTimes: ["Sat 1:00-1:30 PM", "Tue 6:00-6:30 PM"],
    auctionDate: undefined,
    priceGuide: "$1.3M - $1.4M",
  },
  {
    id: "prop_004",
    address: "156 King Street, Newcastle NSW 2300",
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    price: 750000,
    landSize: 580,
    buildingSize: 220,
    yearBuilt: 1960,
    features: [
      "Large block",
      "Original character",
      "Renovation potential",
      "Quiet street",
    ],
    description: "Solid brick home on large block with excellent renovation potential.",
    images: ["https://via.placeholder.com/400x300?text=Newcastle+House"],
    listingAgent: "David Kim - First National Newcastle",
    inspectionTimes: ["Sat 10:00-10:30 AM", "Wed 5:00-5:30 PM"],
    auctionDate: undefined,
    priceGuide: "$720,000 - $780,000",
  },
]

export const SEED_SETTLEMENTS = [
  {
    id: "settle_001",
    propertyId: "prop_001",
    propertyAddress: "123 Collins Street, Melbourne VIC 3000",
    buyerName: "James & Lisa Thompson",
    sellerName: "Melbourne Property Investments Pty Ltd",
    purchasePrice: 850000,
    contractDate: "2024-12-15",
    settlementDate: "2025-02-14",
    financeApprovalDue: "2025-01-15",
    inspectionDue: "2025-01-08",
    status: "on_track" as const,
    daysToSettlement: 28,
    milestones: [
      { name: "Contract Signed", date: "2024-12-15", status: "completed" },
      { name: "Building & Pest Inspection", date: "2025-01-08", status: "pending" },
      { name: "Finance Approval", date: "2025-01-15", status: "pending" },
      { name: "Final Inspection", date: "2025-02-12", status: "upcoming" },
      { name: "Settlement", date: "2025-02-14", status: "upcoming" },
    ],
    conveyancer: "Sarah Mitchell - Mitchell Legal Services",
    mortgageBroker: "Tom Chen - Premium Finance Solutions",
    riskFactors: [],
  },
  {
    id: "settle_002",
    propertyId: "prop_002",
    propertyAddress: "45 Ocean Drive, Bondi Beach NSW 2026",
    buyerName: "Alexandra Rodriguez",
    sellerName: "The Johnson Family Trust",
    purchasePrice: 2100000,
    contractDate: "2024-11-20",
    settlementDate: "2025-01-25",
    financeApprovalDue: "2024-12-20",
    inspectionDue: "2024-12-01",
    status: "at_risk" as const,
    daysToSettlement: 9,
    milestones: [
      { name: "Contract Signed", date: "2024-11-20", status: "completed" },
      { name: "Building & Pest Inspection", date: "2024-12-01", status: "completed" },
      { name: "Finance Approval", date: "2024-12-20", status: "delayed" },
      { name: "Final Inspection", date: "2025-01-23", status: "upcoming" },
      { name: "Settlement", date: "2025-01-25", status: "at_risk" },
    ],
    conveyancer: "Robert Kim - Eastern Suburbs Conveyancing",
    mortgageBroker: "Lisa Park - Coastal Finance Group",
    riskFactors: [
      "Finance approval delayed",
      "Lender requesting additional documentation",
    ],
  },
  {
    id: "settle_003",
    propertyId: "prop_003",
    propertyAddress: "78 Chapel Street, South Yarra VIC 3141",
    buyerName: "Marcus & Jennifer Wu",
    sellerName: "Prestige Developments Melbourne",
    purchasePrice: 1350000,
    contractDate: "2024-10-30",
    settlementDate: "2025-01-30",
    financeApprovalDue: "2024-11-30",
    inspectionDue: "2024-11-15",
    status: "completed" as const,
    daysToSettlement: 0,
    milestones: [
      { name: "Contract Signed", date: "2024-10-30", status: "completed" },
      { name: "Building & Pest Inspection", date: "2024-11-15", status: "completed" },
      { name: "Finance Approval", date: "2024-11-28", status: "completed" },
      { name: "Final Inspection", date: "2025-01-28", status: "completed" },
      { name: "Settlement", date: "2025-01-30", status: "completed" },
    ],
    conveyancer: "Amanda Foster - Foster & Associates",
    mortgageBroker: "Chris Taylor - Melbourne Mortgage Solutions",
    riskFactors: [],
  },
]

export const SEED_DOCUMENTS = [
  {
    id: "doc_001",
    settlementId: "settle_001",
    type: "contract" as const,
    title: "Contract of Sale - 123 Collins Street",
    description:
      "Standard Victorian contract of sale with special conditions for apartment purchase",
    keyPoints: [
      "30-day settlement period",
      "Subject to finance approval",
      "Building inspection clause included",
      "Vendor to provide Section 32 statement",
    ],
    riskFlags: [],
    complianceStatus: "compliant" as const,
    uploadDate: "2024-12-15",
  },
  {
    id: "doc_002",
    settlementId: "settle_002",
    type: "building_report" as const,
    title: "Building & Pest Inspection - 45 Ocean Drive",
    description: "Comprehensive building and pest inspection report",
    keyPoints: [
      "Minor termite activity detected in rear deck",
      "Roof tiles require maintenance",
      "Electrical system in good condition",
      "Plumbing updated recently",
    ],
    riskFlags: ["Termite treatment recommended within 6 months"],
    complianceStatus: "requires_review" as const,
    uploadDate: "2024-12-01",
  },
  {
    id: "doc_003",
    settlementId: "settle_001",
    type: "finance_approval" as const,
    title: "Loan Pre-Approval - Commonwealth Bank",
    description: "Conditional loan approval subject to valuation",
    keyPoints: [
      "Approved amount: $680,000",
      "Interest rate: 6.24% p.a.",
      "30-year term",
      "Subject to satisfactory valuation",
    ],
    riskFlags: [],
    complianceStatus: "compliant" as const,
    uploadDate: "2025-01-10",
  },
]

export const MARKET_DATA = {
  melbourne_cbd: {
    suburb: "Melbourne CBD",
    postcode: "3000",
    medianPrice: {
      apartment: 650000,
      house: 1200000,
      townhouse: 950000,
    },
    priceGrowth: {
      quarterly: 2.1,
      yearly: 8.5,
      fiveYear: 45.2,
    },
    daysOnMarket: 32,
    auctionClearanceRate: 68,
    rentalYield: 4.2,
    demographics: {
      medianAge: 29,
      medianIncome: 85000,
      populationGrowth: 3.2,
    },
  },
  bondi_beach: {
    suburb: "Bondi Beach",
    postcode: "2026",
    medianPrice: {
      apartment: 1100000,
      house: 2800000,
      townhouse: 1800000,
    },
    priceGrowth: {
      quarterly: 1.8,
      yearly: 12.3,
      fiveYear: 52.1,
    },
    daysOnMarket: 28,
    auctionClearanceRate: 75,
    rentalYield: 3.1,
    demographics: {
      medianAge: 35,
      medianIncome: 95000,
      populationGrowth: 1.8,
    },
  },
}
